### ISSUE TITLE
ModuleNotFoundError launching pangtreevis

### ISSUE THREAD

**Issue by propan2one** [meoke/pangtreevis#8]
Hi guys !

I'm working on viral genomic diversity and I'm interesting to test PangTree to produce an affinitytree. So I started to play with pangtreebuild. I get the results for the example alignment of 160 Ebola virus sequences and it's work perfectly. However when I try do visualize this results with pantreevis, I get this module error when I started to launch the dash application with `python3 run.py`

```
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from dash_app.app import app
  File "/export/home/delmotte/Software/pangtreevis/dash_app/app.py", line 6, in <module>
    from .layout import layout_ids, pages
  File "/export/home/delmotte/Software/pangtreevis/dash_app/layout/pages.py", line 4, in <module>
    from pangtreebuild.output.PangenomeJSON import PangenomeJSON
ModuleNotFoundError: No module named 'pangtreebuild.output'
```

I tried to solved it myself but python language is not the one I'm most comfortable with. I check for the package and normaly it should work, you can find it below.

[pip_list.txt](https://github.com/meoke/pangtreevis/files/4580944/pip_list.txt)

Many thanks in advance
Propan2one

**Comment by pknut** [comment]
Hi!
We stopped supporting this version of the code and moved to https://github.com/PangTree. Please check if you have the same error on the current version. : )
